import { NextRequest, NextResponse } from 'next/server';
import { getSessionUserId, supabaseAdmin } from '@/lib/supabase/server';
import PptxGenJS from 'pptxgenjs';

export const runtime = 'nodejs';

export async function GET(req: NextRequest) {
  try {
    const userId = await getSessionUserId();
    if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const sessionId = req.nextUrl.searchParams.get('session_id');
    if (!sessionId) return NextResponse.json({ error: 'session_id required' }, { status: 400 });

    const { data: session } = await supabaseAdmin
      .from('idea_sessions')
      .select('id, idea_title, user_id')
      .eq('id', sessionId)
      .single();

    if (!session || session.user_id !== userId) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { data: slides } = await supabaseAdmin
      .from('ppt_slides')
      .select('*')
      .eq('session_id', sessionId)
      .order('slide_number', { ascending: true });

    if (!slides || slides.length === 0) {
      return NextResponse.json({ error: 'PPT slides not ready yet' }, { status: 404 });
    }

    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_16x9';
    pptx.title = session.idea_title || 'IdeaForge Pitch Deck';
    pptx.author = 'IdeaForge';

    pptx.defineSlideMaster({
      title: 'IDEAFORGE_MASTER',
      background: { color: '0A0A0F' },
      objects: [
        { rect: { x: 0, y: 6.9, w: '100%', h: 0.1, fill: { color: '6366F1' } } },
        {
          text: {
            text: 'IdeaForge',
            options: { x: 8.5, y: 6.95, w: 1.2, h: 0.2, fontSize: 8, color: '6366F1', align: 'right' },
          },
        },
      ],
    });

    slides.forEach((slide) => {
      const s = pptx.addSlide({ masterName: 'IDEAFORGE_MASTER' });

      if (slide.layout === 'cover') {
        s.addText(slide.title || '', {
          x: 0.5,
          y: 2.2,
          w: 9,
          h: 1,
          fontSize: 44,
          bold: true,
          color: 'FFFFFF',
          align: 'center',
        });
        s.addText(slide.content || '', {
          x: 0.5,
          y: 3.4,
          w: 9,
          h: 0.8,
          fontSize: 20,
          color: '94A3B8',
          align: 'center',
          italic: true,
        });
        s.addText('Generated by IdeaForge', {
          x: 0.5,
          y: 5.5,
          w: 9,
          h: 0.4,
          fontSize: 12,
          color: '6366F1',
          align: 'center',
        });
      } else {
        s.addText(`${slide.slide_number}. ${slide.title || ''}`, {
          x: 0.5,
          y: 0.3,
          w: 9,
          h: 0.7,
          fontSize: 28,
          bold: true,
          color: 'FFFFFF',
        });
        s.addShape(pptx.ShapeType.line, {
          x: 0.5,
          y: 1.1,
          w: 9,
          h: 0,
          line: { color: '6366F1', width: 2 },
        });
        s.addText(slide.content || '', {
          x: 0.5,
          y: 1.3,
          w: 9,
          h: 5,
          fontSize: 14,
          color: 'CBD5E1',
          valign: 'top',
          breakLine: true,
          wrap: true,
        });
        if (slide.speaker_notes) {
          s.addNotes(slide.speaker_notes);
        }
      }
    });

    const buffer = (await pptx.write({ outputType: 'nodebuffer' })) as Buffer;
    const filename = `${(session.idea_title || 'ideaforge-pitch').replace(/\s+/g, '-').toLowerCase()}.pptx`;

    return new NextResponse(new Uint8Array(buffer), {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': buffer.length.toString(),
      },
    });
  } catch (error) {
    console.error('PPT generation error:', error);
    return NextResponse.json({ error: 'PPT generation failed' }, { status: 500 });
  }
}
